title: Wiki
host: 'http://localhost'
port: 80
paths:
  repo: ./repo
  data: ./data
uploads:
  maxImageFileSize: 3
  maxOtherFileSize: 100
lang: en
public: false
auth:
  defaultReadAccess: false
  local:
    enabled: true
  google:
    enabled: false
    clientId: GOOGLE_CLIENT_ID
    clientSecret: GOOGLE_CLIENT_SECRET
  microsoft:
    enabled: false
    clientId: MS_APP_ID
    clientSecret: MS_APP_SECRET
  facebook:
    enabled: false
    clientId: FACEBOOK_APP_ID
    clientSecret: FACEBOOK_APP_SECRET
  github:
    enabled: false
    clientId: GITHUB_CLIENT_ID
    clientSecret: GITHUB_CLIENT_SECRET
  slack:
    enabled: false
    clientId: SLACK_CLIENT_ID
    clientSecret: SLACK_CLIENT_SECRET
  ldap:
    enabled: true
    url: ldap://172.16.0.1:389
    bindDn: CN=wikiadmin,OU=Organizemanagement,OU=THiNKNET,DC=local,DC=thinknet,DC=co,DC=th
    bindCredentials:  Th1nK@w1k1@dmin
    searchBase: OU=engineering,OU=thinknet,DC=local,DC=thinknet,DC=co,DC=th
    searchFilter: (&(objectcategory=person)(objectclass=user)(|(samaccountname={{username}})(mail={{username}})))
    tlsEnabled: false
  azure:
    enabled: false
    clientID: APP_ID
    clientSecret: APP_SECRET_KEY
    resource: '00000002-0000-0000-c000-000000000000'
    tenant: 'YOUR_TENANT.onmicrosoft.com'
sessionSecret: f30e0a97aff8de2728dca102d8c817d1c2868c32eeb79fbc1fe8cd58e0651a0e
db: 'mongodb://wiki-mongo:27017/wiki'
git: false

# ---------------------------------------------------------------------
# Features
# ---------------------------------------------------------------------
# You can enable / disable specific features below

features:
  linebreaks: true
  mathjax: true

# ---------------------------------------------------------------------
# External Logging
# ---------------------------------------------------------------------

externalLogging:
  bugsnag: false
  loggly: false
  papertrail: false
  rollbar: false
  sentry: false

# ---------------------------------------------------------------------
# Color Theme
# ---------------------------------------------------------------------

theme:
  primary: indigo
  alt: blue-grey
  footer: blue-grey
  code:
    dark: true
    colorize: true
